AllCops:
  NewCops: disable
  SuggestExtensions: false
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - '.bundle/**/*'
    - 'vendor/**/*'
    - './spec/fixtures/**/*'
    - Gemfile
  TargetRubyVersion: 3.2
  DisplayCopNames: true

Bundler:
  Enabled: false

Naming:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumberedParameters:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning

Lint/EmptyBlock:
  Enabled: false
