#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'rack/contrib'
require 'webrick'
require 'diver_down'
require 'diver_down-web'

definition_dir = ENV.fetch('DIVER_DOWN_DIR')
module_store = DiverDown::Web::ModuleStore.new(ENV.fetch('DIVER_DOWN_MODULE_STORE'))

app = Rack::JSONBodyParser.new(
  DiverDown::Web.new(definition_dir:, module_store:)
)

begin
  # Rack 2.0
  require 'rack'
  require 'rack/server'
  Rack::Server.new(app:, server: :webrick).start
rescue LoadError
  # Rack 3.0
  require 'rackup'
  Rackup::Server.new(app:, server: :webrick).start
end
